### ISSUE TITLE
关于ModuleNotFoundError错误

### ISSUE THREAD

**Issue by szy0syz** [Coder-JJ/rc-leaflet#1]
你好，大佬，今天把rc-leaflet集成到ant design pro里，报了如下错误：

```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve 'images/layers-2x.png' in '/Users/gtkj1/git/gtkj-web-admin/node_modules/leaflet/dist'
    at /Users/gtkj1/git/gtkj-web-admin/node_modules/webpack/lib/Compilation.js:888:10
    at /Users/gtkj1/git/gtkj-web-admin/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /Users/gtkj1/git/gtkj-web-admin/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /Users/gtkj1/git/gtkj-web-admin/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /Users/gtkj1/git/gtkj-web-admin/node_modules/neo-async/async.js:2830:7
    at /Users/gtkj1/git/gtkj-web-admin/node_modules/neo-async/async.js:6877:13
    at /Users/gtkj1/git/gtkj-web-admin/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /Users/gtkj1/git/gtkj-web-admin/node_modules/enhanced-resolve/lib/Resolver.js:184:12
    at /Users/gtkj1/git/gtkj-web-admin/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/gtkj1/git/gtkj-web-admin/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/gtkj1/git/gtkj-web-admin/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5
    at /Users/gtkj1/git/gtkj-web-admin/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/gtkj1/git/gtkj-web-admin/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/gtkj1/git/gtkj-web-admin/node_modules/enhanced-resolve/lib/Resolver.js:238:5
    at eval (eval at create (/Users/gtkj1/git/gtkj-web-admin/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/gtkj1/git/gtkj-web-admin/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38

 @ ./node_modules/rc-leaflet/es/components/RCMap/index.js 25:0-34
 @ ./node_modules/rc-leaflet/es/components/index.js
 @ ./src/pages/map/editor/index.tsx
 @ ./src/pages/.umi/router.js
 @ ./src/pages/.umi/umi.js
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js
```

我去leaflet官网仓库把 layers-2x.png下载后放到 lib/assets/images/layers-2x.png 后重新打包还是报错~
 
又看了下 import 'leaflet/dist/leaflet.css' ，进包里重新build好像缺少文件。😂

**Comment by Coder-JJ** [comment]
开个Git仓库贴出一个完整的包括webpack配置和可以重现该问题的示例代码的项目，方便我帮你查看问题。

在我本地，我测了create-react-app和parcle，不管是开发模式还是生产环境，都没有重现你所说的Bug。

**Comment by szy0syz** [comment]
好的，我现在在家，换个环境尝试重现下看看。

**Comment by szy0syz** [comment]
大佬，已经复现，仓库地址如下：
https://github.com/szy0syz/rc-leaflet-test1

```
error  in ./node_modules/leaflet/dist/leaflet.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve 'images/layers-2x.png' in '/Users/jerry/Git/rc-leaflet-test1/node_modules/leaflet/dist'
    at factory.create (/Users/jerry/Git/rc-leaflet-test1/node_modules/webpack/lib/Compilation.js:888:10)
    at factory (/Users/jerry/Git/rc-leaflet-test1/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
    at resolver (/Users/jerry/Git/rc-leaflet-test1/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/jerry/Git/rc-leaflet-test1/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/jerry/Git/rc-leaflet-test1/node_modules/neo-async/async.js:2830:7
    at /Users/jerry/Git/rc-leaflet-test1/node_modules/neo-async/async.js:6877:13
    at normalResolver.resolve (/Users/jerry/Git/rc-leaflet-test1/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/jerry/Git/rc-leaflet-test1/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/jerry/Git/rc-leaflet-test1/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/jerry/Git/rc-leaflet-test1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/jerry/Git/rc-leaflet-test1/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/jerry/Git/rc-leaflet-test1/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/jerry/Git/rc-leaflet-test1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/Users/jerry/Git/rc-leaflet-test1/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/jerry/Git/rc-leaflet-test1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/Users/jerry/Git/rc-leaflet-test1/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)

 @ ./node_modules/rc-leaflet/es/components/RCMap/index.js 25:0-34
 @ ./node_modules/rc-leaflet/es/components/index.js
 @ ./src/pages/Welcome.tsx
 @ ./src/pages/.umi/router.js
 @ ./src/pages/.umi/umi.js
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js
```

**Comment by Coder-JJ** [comment]
这是`antd pro`配置的问题，或者说是`umi`的问题。

给你找到了相关的解决办法，对方也是在`antd pro`中使用`leaflet`，跟你一样。

[ant-design-pro/issues/3586](https://github.com/ant-design/ant-design-pro/issues/3586)
[umi/issues/1369](https://github.com/umijs/umi/issues/1369)

希望对你有帮助。

**Comment by szy0syz** [comment]
多谢~
